### ISSUE TITLE
Android 12?

### ISSUE THREAD

**Issue by asup20cs** [rufus582/android_device_recovery_samsung_m31s#1]
Is this for the latesr android 12 build or android 11 as if Yillie?

**Comment by rufus582** [comment]
Same as Yillie's

**Comment by asup20cs** [comment]
i built the twrp for android 12 of m31s, but i cant flash it, since fastboot doesnt work on samsung devices. please help me out. i have been trying to get the custom recovery for months now

**Comment by asup20cs** [comment]
if you have built twrp recovery for android 12 please attach it.

**Comment by rufus582** [comment]
> if you have built twrp recovery for android 12 please attach it.

Why build for A12 when you can perfectly run the A11 build?



> i built the twrp for android 12 of m31s

According to what Yillie said, A12 build won't work on Exynos 9611. We probably need to have a more recent kernel version, which is not possible, unless Samsung wants to build that for us, which is never gonna happen

**Comment by asup20cs** [comment]
looks like i did mistake. see, what i did is, i took the latest twrp manifest for android 12 and used your tree, and it successfully built.
what do you think it can be?
here is the abomination that i got
https://xfl.jp/p6KEpw

i swear to god, i have been trying since months to get the twrp. i even rented azure to build it. but the vbmeta is causing a lot of issues. please dont mind if i ask the stupid questions.
will A11 twrp work on A12? will i need A11 android device?
i some how installed the afaneh92 build of twrp for A11 on 12, but cant perform anything
will i be able to flash GSI's using the twrp?

**Comment by rufus582** [comment]
> i took the latest twrp manifest for android 12 and used your tree, and it successfully built. what do you think it can be?

Just use the A11 manifest and it will boot. Builds using A12 manifest won't boot

> will A11 twrp work on A12?

Yes

> will i need A11 android device? 

Not needed

> will i be able to flash GSI's using the twrp?

Ofcourse

**Comment by asup20cs** [comment]
if you have the twrp  and the vbmeta for samsung m31s, please link it. and thank you, very kind of you to answer my stupid questions.

**Comment by asup20cs** [comment]
sorry to bother you again, but i am still getting vbmeta errors while flashing on the A11 os too. it will be really helpful if you could just help me out. please.

**Comment by rufus582** [comment]
You have M31s and telegram? Then join this group. I'll be more active there to help u out, than here.
https://t.me/samsungm31sup
